spring.application.name=Manease

spring.datasource.url=jdbc:postgresql://localhost:5432/manease
spring.datasource.username=manease
spring.datasource.password=manease_secret

spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/changelog.xml
spring.liquibase.default-schema=public
spring.liquibase.contexts=prod, test