spring.application.name=Manease

spring.datasource.url=jdbc:postgresql://localhost:5432/manease
spring.datasource.username=manease
spring.datasource.password=manease_secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect