spring.application.name = ManeaseProducerService

spring.datasource.url=jdbc:postgresql://localhost:5432/manease_producer_service
spring.datasource.username=manease_producer_service
spring.datasource.password=manease_producer_service_password
spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.liquibase.contexts=prod, test